### ISSUE TITLE
Room Moderator

### ISSUE THREAD

**Issue by tunckaany88** [eyeson-team/api#106]
Hi,

Is it possible to create a room moderator role? If it is how can we create?

The reason i need is i will use eyeson at my new startup which is about hosting live events, selling tickets etc.

If there is no moderator (event host) anyone can do anything like muting others, opening cam & mic etc.

Please show me the way to control it. Thanks.

**Comment by unused** [comment]
We currently do not restrict participants but you can implement any role management by building a [custom user interface](https://eyeson-team.github.io/js-docs/overview/) and a middleware to proxy authorized control. However when dealing with events the common case is to [broadcast the video conference](https://eyeson-team.github.io/api/api-reference/#broadcast) rather than having viewers to join as active participants. Please do not hesitate to leave a comment if you have any further questions on this. Best wishes!
