### ISSUE TITLE
possibility to change the room video resolution to a 16:9 aspect ratio 

### ISSUE THREAD

**Issue by guymoller** [eyeson-team/api#112]
I understand from your documentation that the room video resolution is in 4:3 aspect ratio:
> Any eyeson room video has a resolution of 1280x960 pixels. Ensure any file uploaded is an alpha interlaced PNG image with a corresponding resolution to avoid any distortions.

is there anyway to control this resolution?

**Comment by unused** [comment]
Due to the [single-stream technology](https://help.eyeson.com/what-is-single-stream-technology) that eyeson services are based on we deliver the same video stream to every participant. This is set to the 4:3 aspect ratio as you mentioned. We understand that this will likely not fit for every application. A switch to 16:9 ratio is on our roadmap but not yet in active development.
