### ISSUE TITLE
Getting 404 in response when get recorded meeting

### ISSUE THREAD

**Issue by talha-hameed** [eyeson-team/api#116]
i am hitting this api to get my recorded meeting but it always return me 404 error code. 

https://api.eyeson.team/recordings/<room id which I get when access token created>

step 1- I create access token with https://api.eyeson.team/rooms/.   (get 201 code)
step 2- I started the recording with https://api.eyeson.team/rooms/access-key/recording.  (get 201 code)
step 3- I stopped the recording with https://api.eyeson.team/rooms/access-key/recording (get 200 code)
step 4- I am getting the recording response by https://api.eyeson.team/recordings/room-id (get 404 code)

I have also tried last step with access key instead of room id

can anyone help me regarding this? what i am doing wrong?

**Comment by unused** [comment]
The recording is post-processed and will not be immediately ready for download when it is stopped. Therefor we recommend to [register a webhook](https://eyeson-team.github.io/api/api-reference/#register-webhooks) in order to receive the proper information as soon as it is available. Do not hesitate to leave a comment or contact if you have any troubles with webhooks or if this process does not match your use case in any way! Best wishes!
