### ISSUE TITLE
Native android app

### ISSUE THREAD

**Issue by stasSuhanov** [eyeson-team/api#118]
Hello. I am an android developer. I would like to integrate the API into my application. Is it possible to integrate it natively? Or perhaps only using a webView. Do you have a sample android app?

**Comment by unused** [comment]
Hi there, nice to hear you plan to make your app use eyeson. You have a great timing, we are about to release mobile development kits this month. I'm happy to leave you a comment after they get published.

For sure you can also go with webviews. Do not hesitate to let me know if you have any specific questions.

**Comment by stasSuhanov** [comment]
OK thanks. I'll be waiting.

**Comment by stasSuhanov** [comment]
I still have a question. How much load can the API support. For example 10 users without video or 5 users with video. Now I can use your API using webRTC. How webRTC supports your technology?

**Comment by stasSuhanov** [comment]
And how does webRTS work with your MCU technology? Where can I learn more about MCU technology?

**Comment by unused** [comment]
A lot of details to this questions are covered by the [eyeson help center](https://help.eyeson.com/eyeson-system-requirements), and many topics are explained in the [eyeson blog](https://blog.eyeson.com/) or [techblog](https://techblog.eyeson.team/)as well.

WebRTC is one of many technologies our services are based on, however with the libraries we provide we take care of the tricky parts like connection handling and device management yet provide interfaces so that you have full control on a meeting session.

The eyeson service [allows up to 100 participants](https://help.eyeson.com/how-many-participants-can-join-a-room) whereas the video podium shows up to 9 people, other users participate with audio or switch to video by audio-detection.

Let me know if you have any further questions!

**Comment by stasSuhanov** [comment]
Hello. Mobile development kits already available? Or is it still in development?

**Comment by unused** [comment]
Hi there, sorry for the waiting time. The packages for iOS and Android are soon to be published, I've already checked this with our mobile team. Looking forward to let you know the details asap!

**Comment by stasSuhanov** [comment]
Thanks for the answer. This is amazing. I'm looking forward to it.

**Comment by unused** [comment]
:see_no_evil: it took way longer than I expected, I'm sorry for that. The [iOS SDK](https://github.com/eyeson-team/ios-sdk) has been [released](https://github.com/eyeson-team/ios-sdk/releases/tag/1.0.1), the Android SDK should follow up pretty soon.

**Comment by stasSuhanov** [comment]
Great! Waiting for android SDK.

**Comment by unused** [comment]
The [Android SDK](https://github.com/eyeson-team/android-sdk) has been [released](https://github.com/eyeson-team/android-sdk/releases/tag/1.0.1).
