### ISSUE TITLE
websocket link

### ISSUE THREAD

**Issue by FredFu0234** [eyeson-team/api#122]
I try to connect to a websocket after creating the room to get notifications.

But what is the correct websocket url?

The api call for creating the room returns mir something like this in the links attribute:
... "links": {
     "self": "https://....",
     "gui": "https://...",
     "self": "https://...",
     "guest_join": "https://...",
     "websocket": "https://api.eyeson.team/rt?access_key=[A SHORT ACCESS KEY]",
}

Why starts this websocket with https:// and not with wss://?
When I change the https:// to wss:// i can connect to this websocket, but I receive only "ping" messages.

The create room api call returns also signaling.options with:
{
    "client_id": "xxx",
    "conf_id": "yyy",
    "auth_token": "long token",
    "endpoint": "wss://sig.eyeson.com/call",
    "stun_servers": [
        "stun:nuts.eyeson.com:3478"
    ],
    "turn_servers": [
        {
            "urls": [
                "turn:nuts.eyeson.com:....",
                "turn:nuts.eyeson.com:....",
                "turns:nuts.eyeson.com:..."
            ],
            "username": "usernamexxx",
            "password": "a passssword"
        }
    ]
}

I can also connect to this endpoint websocket with the credentials but there I receive no messages.

To what websocket do I have to connect to receive messages about a room?

**Comment by unused** [comment]
You can adapt the link provided in `links.websocket` and change the protocol from `https` to `wss` depending on your environment. The connection uses the [action cable protocol](https://docs.anycable.io/misc/action_cable_protocol) for communication, you can subscribe to a `RoomChannel` and a `UserChannel` to receive broadcasted messages.

```json
{
  "command": "subscribe",
  "identifier": "{\"channel\":\"RoomChannel\"}"
}
```

```json
{
    "command": "subscribe",
    "identifier": "{\"channel\":\"UserChannel\"}"
}
```

In order to see a sample communication you can always check the default web UI and network messages, e.g. with Chrome: Open developer tools before starting a meeting, join a meeting with the default web UI, switch to tab "Network", select WS, click the WS connection request and follow the websocket message transfer.

Let me know if you need any further details!

**Comment by FredFu0234** [comment]
I sent this two commends to the websocket and I receive now "RoomChannel" updates. But I do not receive any message when a guest joins the room.

**Comment by FredFu0234** [comment]
I tried also webhooks to receive room_updates. I thought I would then receive also notification for joining and leaving users. But I receive also only notifications when the room ist created and shutdown.

**Comment by FredFu0234** [comment]
When I add the room id to the subscribe RoomChannel, I receive some more events. But no user events.

{
  "command": "subscribe",
  "identifier": "{\"channel\":\"RoomChannel\", \"id\": \"ROOM_ID\"}"
}

Then I receive events from type "playback_update" - eg. when giphys are displayed. But no user events.

**Comment by unused** [comment]
ref #123
