### ISSUE TITLE
Webhooks - Signature request verification for "recording_update" event.

### ISSUE THREAD

**Issue by KurnosovNikita** [eyeson-team/api#124]
Dear Team,

Our team is investigating Eyeson for potential use in production.
Now, we are facing a problem with validating signature for incoming request with "recording_update" type.

We've found the same problem that was created last year and unfortunately there is no solution in it.
https://github.com/eyeson-team/api/issues/115

Please see the given link above as an example of the situation we are facing, it is absolutely identical.
Also signature SHA256 HMAC validation for "room_update" type works fine.

Here is the code that is validating any incoming request.
 ```
  router.post('/webhooks/room-update', async (req, res) => {
    const signature = req.headers['x-eyeson-signature'];
    const hmac = crypto
        .createHmac('sha256', eyesonApiKey)
        .update(JSON.stringify(req.body))
        .digest("hex");

    if (signature !== hmac) {
        ...
      }
      ...
```

Please, let me know if you need any additional details.
Many thanks!

**Comment by unused** [comment]
Hi there, in order to verify the signature you have to use the untouched raw response body. From your example I'd expect some middleware parsing the JSON response, a `stringify` will likely differ to the original JSON (e.g. key order might be different, whitespaces might have been stripped or added). Your snippet looks like express framework to me, so I've setup a quick example for you that verifies the signature properly:

```javascript
const express = require('express')
const app = express()
const port = 3003
const bodyParser = require("body-parser");

const crypto = require('crypto');
const eyesonApiKey = process.env.API_KEY;

app.use(bodyParser.text({ type: '*/*' }))

app.post('/webhooks/room-update', (req, res) => {
   const signature = req.headers['x-eyeson-signature'];

  const hmac = crypto
    .createHmac('sha256', eyesonApiKey)
    .update(req.body)
    .digest('hex');

  console.info('same: ', signature === hmac);
  console.info('signature: ', signature);
  console.info('hmac: ', hmac);
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)

  if (!eyesonApiKey) {
    console.error('Error: API_KEY is missing');
    console.info('Usage: API_KEY=... npm start');
    throw 'Missing API key';
  }
});
```

Depending on your app you can for sure also add any other middleware, like some that stores your raw body in an additional attribute, and a JSON parser such that you can still access the JSON data conveniently.

Let me know if you have any further questions on this!

**Comment by KurnosovNikita** [comment]
Hi @unused,

Thank you for your reply.
You were right, so the issue was in `express.json()` parser that was used as a middleware.

I'll just write a quick solution below, in case anyone runs into this issue in the future with the same parser.
This will help avoid overwriting any existing middleware and keep the raw request body available in the request.

```javascript
  app.use(express.json({
    verify: (req, res, buf) => {
      req.rawBody = Buffer.from(buf).toString();
    }
  }));
```
Then we can use `rawBody` to generate `hmac`.

**Comment by unused** [comment]
Thank you for sharing, that is awesome :heart_eyes_cat:
