### ISSUE TITLE
The documentation should explain difference between user and guest user

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/api#125]
Where: https://eyeson-team.github.io/api/api-reference/#user-and-guest-user

What: Bellow the headline it should state a sentence what the difference is. As far as I am aware of it is essential to create at least the meeting host (or all required participants) as normal user so that the meeting doesn't close unexpectedly. Guest users are meant to be created during the meeting. It would also be nice to write if the response of a guest create is a subset of a create user request (I now check it field by field myself)

Also:
I think there is no way to create a normal user after creating the room. Not sure why and I'd request to change that.

**Comment by unused** [comment]
First of all I want to thank you for your input. This is a very valuable feedback that we're glad to receive and discuss in very details on how to improve our services in planning meetings and workshops. We strive to constantly enhance our developers experience although some parts will be published just in the (quite) later releases. 

For the current state of the service there are some things to consider that will solve your issue(s), including #126 and #127. The eyeson service is not meant to provide management of users, meeting or rooms but offers to create and control modern video conferences. You can think of a user as a **temporary access to one meeting**, you will only want to have it at the moment your application user is actually going to use it. This architectural design brings less dependency for your software and provides you with the flexibility of handling any user specific requirement in your system. You only have to interact with eyeson as soon as a participant wants to use the video communication. In order to ensure participants end up in the same meeting [use the room identifier](https://eyeson-team.github.io/api/api-reference/#eyeson-room).

```sh
$ curl -X POST -H "Authorization: $API_KEY" -d "id=standup" -d "user[name]=Alice" "https://api.eyeson.team/rooms" | jq '.links.gui'
$ curl -X POST -H "Authorization: $API_KEY" -d "id=standup" -d "user[name]=Bob" "https://api.eyeson.team/rooms" | jq '.links.gui'
```

Guests are regular users, the only difference is that a meeting provides a temporary authentication (guest-token) to join new users, without the need of API-key authentication. Therefor a client application can allow to invite users on-the-fly without additional communication back to your servers. In server-to-server communication the guest-token is unneeded.

Do not hesitate to leave a comment if you have any further questions!
