### ISSUE TITLE
Joining a room as a guest and setting a name using the quick-join link

### ISSUE THREAD

**Issue by Clemens-U** [eyeson-team/api#138]
Hello Team! I am currently evaluating the video API.

I have a quick question about joining a room as a guest and setting a name. I can successfully create a room using the API. But when I try to join a room as a guest, using the guest token, I can’t figure out how to set the (user) name in advance. The request always opens a page to set a name before joining.
 
I tried to join the room, creating the „quick-join“ link in the following way:
 
https://app.eyeson.team/?guest=<token>&name=foo
https://app.eyeson.team/?guest=<token>&user[name]=foo
 
This works, but both ways only redirect to a page where I need to specify a name.
Is it possible to skip the page to enter a name manually as a guest?

Kind regards
Clemens

**Comment by unused** [comment]
Hi there! In order to join users to a single meeting please set a unique room identifier `id` attribute.

```sh
$ curl -X POST \
  -H "Authorization: $API_KEY" \
  -d "id=team-alice-and-bob" \
  -d "user[name]=Alice" \
  "https://api.eyeson.team/rooms"

$ curl -X POST \
  -H "Authorization: $API_KEY" \
  -d "id=team-alice-and-bob" \
  -d "user[name]=Bob" \
  "https://api.eyeson.team/rooms"
```

Use the guest token to join new users during an active meeting on-the-fly. It does not require API-key based authentication and can therefor be used independently on a client-side.

Please do not hesitate to leave a comment if you have any further questions.
