### ISSUE TITLE
Getting billable time per meeting

### ISSUE THREAD

**Issue by nomatter01** [eyeson-team/api#140]
Hello,
is there some way to use the API to get a list of billable minutes per meeting id?
The thing is, that there could be multiple meetings with the same meeting_id spawned (users connect to the same meeting multiple times).

The only way the email support told me to do this is by using the webhooks.
This is not ideal, since this way we will loose some data when the webhook endpoint is down.

But even if we do it using webhooks, I am not sure it will work.
I thought I could maybe use the shutdown: true room_update event to track lengths of meetings. But in those events the started_at time of the meeting is null and no end_time for the meeting is contained (only a timestamp).
Also, you are sending those webhooks multiple times per meeting and there is no safe way to distinguish, is there?

Is there any way to do this I am missing?

**Comment by opusonline** [comment]
Hi. Thanks for your question. I need to collect some information and get back to you asap.

**Comment by opusonline** [comment]
There's no way to use the API to get a list of billable minutes per meeting id. The support is right, the only way of doing this is using webhooks.

Here's how you can derive meeting minutes from webhooks. You receive multiple webhooks and they are related via the `room.id`. The first webhook with `room.ready: true` has a timestamp, and the first webhook with `room.shutdown: true` has a timestamp. Substract the first timestamp from the later one and you have the exact seconds of the operational meeting.

If you need to calculate operational meeting time on a user basis (because you mentioned "multiple meetings with the same meeting_id spawned"), you can use the unofficial webhook type `participant_update`. The `participant.online` parameter tells you if the participant has joined or left the meeting. These webhooks also provide a timestamp in seconds.

For questions about billing you can reach out to sales@eyeson.com.

Please do not hesitate to leave a comment if you have any further questions.
