### ISSUE TITLE
i am trying to connect o your websockets but it always give me this error ist blocked from your side ?

### ISSUE THREAD

**Issue by ashrafJebril** [eyeson-team/api#15]
localhost/:1 Access to XMLHttpRequest at 'https://api.eyeson.team/rt/info?access_key=5c9a3f9425d9a50010008018/&t=1554381574712' from origin 'http://localhost:3000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by unused** [comment]
If you are using the eyeson JavaScript package you don't have setup the real-time connection via websockets, you are already receiving every websocket event with the `eyeson.onEvent` listener.

**Comment by romashauk** [comment]
well, I received the same error 
My case is the following
I am using eyeson UI but I have my own chat with participants.
I would like to get remove_user event in that chat. 
Any ideas @unused ?

**Comment by unused** [comment]
Can you give more details on your issue? Where do you see this? What is the context?

If you use `onEvent` you already receive all messages that are sent via real-time connection. There is no need to connect a second time to the websockets channel. I've extended the [react example](https://github.com/eyeson-team/react-web-gui-example/commit/10e2162c23ca31ac1daf01c72f7927b974bdcbf3) with a debugging statement so you can check for events there. The `remove_user` event is received whenever a participants leaves.

![Screenshot from 2021-03-02 07-33-39](https://user-images.githubusercontent.com/59397/109608474-3a300300-7b2a-11eb-9057-abee831713e1.png)

**Comment by romashauk** [comment]
@unused Basically, my case is following: 
I am using eyeson UI but I have my own chat with participants.
So, I am joining to a room without using eyeson.start.
1. I am sending the POST method to https://api.eyeson.team/rooms with the required data.
2. I received the link as a response.
3. I put this link to the Iframe and use it on my app. 
4. I added my custom chat instead of yours. Also, there is a tab participants.
But the problem with that is that I cannot track properly if a user has disconnected from the room. 
eyeson.onEvent receive the event 'remove_user', what can I use in my case? 

Thanks in advance

**Comment by unused** [comment]
I'd recommend **not** to use an iframe as it takes all control from you. You can easily build a custom UI tough. The eyeson JS package merges event messages from different channels and sums up details you would miss if directly connecting to those.
