### ISSUE TITLE
web hook 

### ISSUE THREAD

**Issue by ashrafJebril** [eyeson-team/api#17]
i have an web hook (room update)
i register a webhook for room_update and track when receiving a room update where shutdown attribute is true.
but my problem i don't receive shutdown date time or time interval for the session?

**Comment by unused** [comment]
Hi! Great you managed to receive the session updates. In order to read the details please use the `started_at` and `ended_at` parameters send via webhook. When needed you can calculate the meeting duration from the date times but keep in mind that there is a 2 minute offset after the last participant left.

**Comment by ashrafJebril** [comment]
![2019-03-27](https://user-images.githubusercontent.com/43233897/56645763-fa26ac00-6686-11e9-865d-e9ede92bcf7b.png)

this is the response from web hook after end the session (shutdown = true) but there is no ended_at

**Comment by unused** [comment]
Thank you for the details. I'm sorry that's right - there is no explicit timestamp provided, so you can set it by the time the webhook is received containing the shutdown information. Please do not hesitate to ask if you have any other question on this!
