### ISSUE TITLE
SFU Mode on Safari/iPhone Not Enabled

### ISSUE THREAD

**Issue by jdeckcurago** [eyeson-team/api#25]
Hello, I worked with Peter today and discovered that SFU mode on Safari/iPhone is not enabled. He explained technically that there is a browser compatibility problem. While we can solve this by using Chrome, this doesn't work for our use case because the users on iPhone will always use Safari.

Another way of saying this is, when a Safari user on an iPhone connects to a one to one meeting, the video picture is side by side which is too small to be useful. We need the user experience to be more like FaceTime which is only achieved on a mobile device when the Chrome web browser is used.

**Comment by jdeckcurago** [comment]
![IMG_D9216CB9F05A-1](https://user-images.githubusercontent.com/59783230/77667897-01fa6a80-6f40-11ea-8fc7-b0cec63190a0.jpeg)

**Comment by jdeckcurago** [comment]
I just tested on a Chrome browser on an iPhone 11 and this is the message I get. So even with Chrome, Eyeson is not working at all. Only with Safari and with Safari SFU mode is not enabled.

**Comment by jdeckcurago** [comment]
![IMG_E8E3F3E54C60-1](https://user-images.githubusercontent.com/59783230/77668150-44bc4280-6f40-11ea-92bf-ed541bb6c617.jpeg)

**Comment by jdeckcurago** [comment]
This is what it looks like on an iPhone 11 using Safari. ^^^

**Comment by unused** [comment]
Hi, nice to meet you! In order to support as many clients as possible we avoid testing for browsers and version but instead try to detect features support by the client on demand. This however is a quite complex task and might give bad response in this case. Thank you for the heads up, we're already looking into this issue and let you know as soon as we figured out any details. Best Wishes!

**Comment by unused** [comment]
Our team had some close look on the problem, unfortunately we did not come up with an easy solution yet. To achieve the same behavior as in the web clients, we need to further investigate the issues on the client. Looking forward to let you know when the problem is solved or in worst case we cannot enforce the requirements of the browser.

**Comment by jdeckcurago** [comment]
Ok, thank you. Please keep us posted.

Best, James

On Apr 1, 2020, at 8:37 AM, Christoph Lipautz <notifications@github.com> wrote:

﻿

Our team had some close look on the problem, unfortunately we did not come up with an easy solution yet. To achieve the same behavior as in the web clients, we need to further investigate the issues on the client. Looking forward to let you know when the problem is solved or in worst case we cannot enforce the requirements of the browser.

**Comment by opusonline** [comment]
Hi, we have good news for you!
The SFU mode on Safari (desktop and mobile) is working now, so the video pictures are not "side-by-side" anymore.
Best regards,
Stefan
