### ISSUE TITLE
API: User Kicking/Muting?

### ISSUE THREAD

**Issue by Nkay** [eyeson-team/api#32]
Dear Team,

I cannot find the following in the docs: 
Am I able to kick someone out of a room?
Can I mute or close the video stream of someone remotely, or only on the client side?

Best Regards,
Simon

**Comment by unused** [comment]
Hi there! We do not have any user/role management in our application so we can focus on providing you with a feature rich media platform rather than complex user handling that in most cases won't match requirements. However you can simply proxy any requests and deal with permissions, roles etc. yourself. In order to control media streams you additionally use a custom user interface as well. Best wishes!
