### ISSUE TITLE
Init Camera

### ISSUE THREAD

**Issue by salgadoperez** [eyeson-team/api#43]
When using the api in my web app and the meeting starts in an iframe, you cannot initialize the camera or microphone. Error: "Allow camera and microphone access in your browser". However, if you enter it directly through the browser, everything is correctly initialized.

![C1](https://user-images.githubusercontent.com/65362345/81967517-07dc0600-95e9-11ea-9a59-f6a020dca119.PNG)

**Comment by salgadoperez** [comment]
allowfullscreen allow="microphone https://app.eyeson.team; camera https://app.eyeson.team" in iframe.

**Comment by Antoni-Lopez** [comment]
Hello,

I'm having the same problem, and any of these two really work:

allowfullscreen allow="microphone https://app.eyeson.team; camera https://app.eyeson.team"
allowfullscreen allow="microphone *; camera *"

This is due to iFrame restrictions on Safari. Did you manage to get it solved?, I can only achieve it if I open up a new window, but I can't within an iframe. It's working fine in Chrome and Firefox, but not in Safari or IE.

Best regards
