### ISSUE TITLE
Suggestion: Mocked API for automatic tests

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/api#44]
Hi! We are working on halloSOPHIA. Timeplan is tight but project that I work on usually get UI tests for core functionality (via selenium puppeteer etc.).

Those tests would very often create rooms and add guests etc. that will never ever be used and all data created will be thrown away right after the test. The API call and response should look valid (parsing the result shouldn't fail) but it wouldn't matter if it would always return the same results and the meetings wouldn't actually work.
-> so a mocked api

In an call with you guys from eyeson I was told that this doesn't yet exist so this is my suggestion :)

**Comment by unused** [comment]
Hi there, maybe there has been some misunderstanding. For all of our projects we do not send any outgoing request during test execution, neither in development or CI jobs. It is a good practice to interrupt or mock such requests and provide a sample or generated response. Please do not hesitate to contact if you have any further questions.

**Comment by codingyourlife** [comment]
> we do not send any outgoing request during test execution

No I mean OUR tests would stress YOUR API.

> It is a good practice to interrupt or mock such requests and provide a sample or generated response

Exactly! It would help if you could provide such a test api which only produces sample responses. But we'll find other ways to solve this if this is not an option.

**Comment by unused** [comment]
Sorry it seems I did not answer this clearly: The common way to do this in your test suite is to mock or interrupt the request and provide some static or dynamic sample response. You have many possibilities how to do this and modern development environments already come with some handy tools. Additionally you want your tests to match your use case, therefor you probably will focus on a part of the API and build your scenarios there.

On the other hand side, some of the reasons offering a "fake api" is a bad idea is that you don't want to use network during your test runs (e.g. cancel a deployment because your CI jobs are failing with connection issues), nor you want to setup and run some fake environment on every development box or test runner.

At eyeson we love automatic testing and do this in various ways. I'd recommend to always stick to the documentation, extract examples there where needed and build your expected responses from them. Another nice approach is to record a single request, remove any credentials related information and build up your fixtures library from this.

Imho there is not much we could additionally provide you for your automatic tests, if you do not think so please let me know so we can discuss this in our team. Thank you and best wishes!
