### ISSUE TITLE
Missing API documentation?

### ISSUE THREAD

**Issue by emiliorcueto** [eyeson-team/api#55]
When comparing the PHP SDK with the Ruby alternative, there are differences in endpoints utilized (E.g. [snapshots](https://github.com/eyeson-team/eyeson-ruby/blob/master/lib/eyeson/snapshot.rb))

I also fail to see where the API exists to lock a room.   This is possible via the UI, but I don't believe it is documented here in the existing API documentation.  _Side Note:  Once a room is locked, can it be "Unlocked" afterwards?_

Another interesting find is that after a guest user is created, the response includes a links object very similar to when a room is originally created.  When joining a room as a guest, it appears the user still has access to several features that should be reserved for members only.  E.g. Broadcast Settings, Recording, Layout, etc

Is there more complete documentation available? Currently the [API repo](https://github.com/eyeson-team/api) does describe several facets of the API as is made clear by the differences in these two SDKs.  It would be very helpful if there were a swagger doc (or similar) that fully describes the available public API.

**Comment by unused** [comment]
Hi, thank you for your feedback! It's nice to see that you compared the packages with the documentation. We do apply some progressive enhancement on our products and provide extensions on demand. Swagger and other documentation generators are great tools, and are of much help when building rather big interfaces. For the eyeson API service we decided not to use any generators as the interface is pretty small but comes partly with quite complex features behind.

Regarding the features mentioned: We do not have any API customers that have any use case for snapshots, that's why we did not take it account for documentation. The lock feature is present in the default web UI provided but unlikely of interest for anyone using the API so we provided only an option to disable the feature. Additionally it's quite new and we have not decided yet if it will stay the way it is, or even if we keep it.

Participants do have no user roles, therefor they have the same access on features. Guests are regular users with minimal limitations. If you require some sort of user management you can easily build your own user interface and proxy requests to handle access control.

If you do have any further questions do now hesitate to leave a comment!

Best wishes!
