### ISSUE TITLE
Error 410 - GONE problem to create a guest

### ISSUE THREAD

**Issue by joaocolganenet** [eyeson-team/api#87]
Hi,

every time I tried to create a new guest the api returned a 410 Gone, 

First of all I created a room like this:
POST https://api.eyeson.team/rooms 
it works and return an "access_key" and a "guest_key".

With the access_key I can start the conference and it works, but when I try to add a new guest
POST https://api.eyeson.team/guests/{access_key}
it returns 401 unauthorized, so I supposed I need to use "guest_key"

but if I try  https://api.eyeson.team/guests/{guest_key} it returns 410 Gone. 

any ideas?
thanks

**Comment by unused** [comment]
The meeting will expire after a short period of time if no one enters. Use the `/rooms` endpoint to join your users, the `/guests` endpoint can be used create new users on-the-fly authenticating with the given guest key rather than having to use the API key. This allows you being able to invite other users client side easily. Best wishes and do not hesitate to leave a comment if you have any further questions.
