### ISSUE TITLE
Recorded videos cannot be played at Safari

### ISSUE THREAD

**Issue by romashauk** [eyeson-team/api#97]
As far as you eyeson uses WebM format for stored videos, Safari doesn't support this format. 
It is quite a problem for users.
Any solutions to that? 
Thanks in advance

**Comment by romashauk** [comment]
One more problem that I came across yesterday. 
We had 2 hours lecture yesterday. The teacher set the layout so everyone sees only him. And he was presenting the screen. 
The first part of the lecture is recorded pretty well, but then we had a 10 minutes break. So, the teacher switch of presenting screen mode and the camera, and after that, he continued to explain materials and share the screen. Everybody sees  his screen, but on the record, it is missing

**Comment by romashauk** [comment]
https://firebasestorage.googleapis.com/v0/b/educate-me-shauk.appspot.com/o/Screen%20Shot%202021-02-04%20at%2012.07.30.png?alt=media&token=a3802f17-0e7b-40de-98c8-9f7a5d5ad065

As you can see there are icons that he is speaking and presenting on the screen. But why on recording there is no his screen.
What I am missing and how to prevent the bug?

**Comment by opusonline** [comment]
Hi,
thank you for your feedback!
We will investigate and get back to you as soon as possible.
Best regards, Stefan

**Comment by romashauk** [comment]
One more time met the second problem. From the very beginning, the host was sharing the screen. But no screen on the recording. How can I fix that or how to prevent this behaviour

**Comment by romashauk** [comment]
Finally, I've got a detailed description of the bug. 
I have recorded a loom-video for you 
https://www.loom.com/share/a43279c150ec4a7fb8c43c527e73bc5f
Please, fix it ASAP

**Comment by unused** [comment]
Thank's for the video, that helps a lot to understand the problem. At first sight it might be some state issue in our UI, we'll have a look as soon as possible and I will forward you any updates.

**Comment by romashauk** [comment]
Hello guys, do you remember about the problems?

**Comment by unused** [comment]
No update yet. I'll let you know when the problem is fixed.

**Comment by romashauk** [comment]
Also, the recorded video is not playable on Mobile at all. Any advice?

**Comment by opusonline** [comment]
Regarding WebM you're right, Safari still doesn't support this format.
Fortunately you can use VLC video player to watch WebM videos. It integrates very nicely on iOS devices, so you can start watching from iOS Safari right away, just select VLC app to open the file.
On Android everything works out of the box since Chrome, Firefox and other browsers do support this video format.
Furthermore you can convert WebM files to MP4 or other formats with tools that are even available online.

Regarding the presenting problem, still no updates yet. I'll let you know as soon as a fix is deployed.

https://www.webmfiles.org/how-to-play-webm-files/
https://www.videolan.org/vlc/
https://cloudconvert.com/webm-converter

**Comment by opusonline** [comment]
Good news!
The missing presentation bug is fixed. Thanks again for reporting to us.
Please do not hesitate to open another issue or leave a comment if you have any further questions.
Best wishes
