### ISSUE TITLE
download recordings

### ISSUE THREAD

**Issue by joaocolganenet** [eyeson-team/api#98]
Hello,

I'm trying to understand how to record a videocall.

First of all I used this: https://eyeson-team.github.io/js-docs/events/#recording

eyeson.send({
  type: 'start_recording',
});

and 
eyeson.send({
  type: 'stop_recording',
});

But once I have closed the recording, how can I download the video?
I was watching this link: https://eyeson-team.github.io/api/api-reference/#recording
but when I try to use the post method it returns 401 unauthorized.

what time can I call that method?
I tried after the videocall and also while it was running but I got the same error (401)

thanks

**Comment by opusonline** [comment]
Hi,
You are pretty close!
In every `recording_update` event you receive the `recording.links.self` endpoint. That's the important one, it includes the `recording.id` which should be stored in your app.
Be aware that `recording.links.download` expires after a certain amount of time!
That's why, in order to download a recording, you should always make a fresh API call to the given endpoint. This API call is not contained in *eyeson-js*, you have to perform the call directly from the API, so make sure to follow the authorization rules and include the API key in the HTTP header (https://eyeson-team.github.io/api/api-reference/#authorization).
In this response you can use the `links.download` URL to download the video.
Please do not hesitate to open another issue or leave a comment if you have any further questions.
Best wishes!
