### ISSUE TITLE
screensharing with safari

### ISSUE THREAD

**Issue by joaocolganenet** [eyeson-team/api#99]
Hello,

we have an strange behavior when you try to stop the screensharing with safari.
If there are only 2 users connected everything works fine.

started
![image](https://user-images.githubusercontent.com/61703328/108825832-cc348a80-75c3-11eb-96e7-537ca19d1cf3.png)
ended
![image](https://user-images.githubusercontent.com/61703328/108827071-6ba64d00-75c5-11eb-895a-d7296f4bdb7d.png)

the problem occurs when you have more then 2 users and you try to stop the screensharing, in this case you see something like this:
![image](https://user-images.githubusercontent.com/61703328/108826600-c5f2de00-75c4-11eb-9c02-d8d4b482ea2f.png)

the same problem occurs if someone enters the call when screen sharing is activated, the screen you would see is like the one above.

I also tried on chrome but it works.

thanks

**Comment by opusonline** [comment]
Hi,
at first, your app looks great, well done!
Since I have no access to your app, I could only test the issue on our apps and there it works nicely with latest Safari (v14.0.3). Unfortunately I couldn't test with BigSur yet, but I try to find a way to do so.
Please have a look at  https://eyeson-team.github.io/react-web-gui-example/ and test with your Safari.
In https://github.com/eyeson-team/react-web-gui-example/blob/master/src/App.js you can see how the screenshare presentation works with *eyeson-js*.
Let me know if you are still experiencing the same issue on the [react-web-gui-example](https://eyeson-team.github.io/react-web-gui-example/).
Thanks!

**Comment by opusonline** [comment]
Just an additional note: I could test with BigSur now and had no issues.

**Comment by opusonline** [comment]
I'm closing this ticket now since there are no updates.

Please do not hesitate to open another issue or leave a comment if you have any further questions.
Best wishes!
